Adds morning warmup to practice power poses
CodeYourFuture/curriculum pull request #1180
Opened 2024-11-07 15:44 UTC by fcaroline2020

## What does this change?

### Common Content?

- [ ] Block/s

### Common Theme?

- [ ] Yes

Issue number: #issue-number

### Org Content?

Module | Sprint | Page Type | Block Type

## Checklist

- [ ] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [ ] I have run my code to check it works
- [ ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Who needs to know about this?

2024-11-08 17:46 UTC, SallyMcGrath requested changes
Oh, hrm, let me think! 🤔 

So - this is one of the most famously debunked bogus findings in the psychology replication crisis and I have strong concerns with introducing it as fact or without that context. The Ted talk is particularly problematic in this way. 

But that's ok  - it doesn't need to be true to be fun. Can you change the energiser to make it clear that there's no evidence that this is anything but a fun game? (It sounds pretty fun and energisey and I don't object to the activity itself!) 

https://www.sciencedaily.com/releases/2019/10/191001110824.htm

2024-11-14 16:29 UTC, fcaroline2020 commented
> Oh, hrm, let me think! 🤔
> 
> So - this is one of the most famously debunked bogus findings in the psychology replication crisis and I have strong concerns with introducing it as fact or without that context. The Ted talk is particularly problematic in this way.
> 
> But that's ok - it doesn't need to be true to be fun. Can you change the energiser to make it clear that there's no evidence that this is anything but a fun game? (It sounds pretty fun and energisey and I don't object to the activity itself!)
> 
> https://www.sciencedaily.com/releases/2019/10/191001110824.htm

I had to do a workshop at my previous job in 2021 that was still teaching this as a part of confident presenting! I did not realize that this was debunked 😆

2024-11-14 16:34 UTC, fcaroline2020 commented
I've added a warning but we can remove this energizer all together if we have better ones with stronger evidence

2024-11-18 08:14 UTC, SallyMcGrath commented on common-content/en/energisers/confident-presenting/index.md
> +> The science behind power poses is not very strong, this is only to get everyone up and moving around!
```suggestion
> This is not proven science. This is just a fun game to get everyone up and moving around!
```

2024-11-18 08:16 UTC, SallyMcGrath commented
> > Oh, hrm, let me think! 🤔
> > So - this is one of the most famously debunked bogus findings in the psychology replication crisis and I have strong concerns with introducing it as fact or without that context. The Ted talk is particularly problematic in this way.
> > But that's ok - it doesn't need to be true to be fun. Can you change the energiser to make it clear that there's no evidence that this is anything but a fun game? (It sounds pretty fun and energisey and I don't object to the activity itself!)
> > https://www.sciencedaily.com/releases/2019/10/191001110824.htm
> 
> I had to do a workshop at my previous job in 2021 that was still teaching this as a part of confident presenting! I did not realize that this was debunked 😆

Yes it keeps coming back - it popped up twice in the PD curriculum last year too. I don't mind people having fun with the power posing - it's clearly popular. But we can't pass it off as science because... not really! 😅

2024-11-18 08:16 UTC, SallyMcGrath approved these changes

2024-11-18 09:35 UTC, merged