SDC Tools sprints 3 and 4
CodeYourFuture/curriculum pull request #1276
Opened 2024-12-30 15:37 UTC by illicitonion

Courseworks are present in https://github.com/CodeYourFuture/Module-Tools/issues

2025-01-22 13:52 UTC, SallyMcGrath requested changes
A few tiny notes. Loving it. So happy to see cowsay hee.

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +    "Identify and explain differences between JavaScript and Python",
```suggestion
    "Compare and contrast differences between JavaScript and Python",
```

Just for the classical style 😛

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +JavaScript and Python are quite similar languages in a lot of ways.
```suggestion
JavaScript and Python have many things in common.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +Most of the differences between them are quite cosmetic. e.g.
```suggestion
Most differences are "cosmetic". Here are some examples of cosmetic differnces:
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +* JavaScript uses `{}` around blocks of code and we optionally _choose_ to indent code, whereas Python uses `:` and _required_ indents.
```suggestion
* JavaScript uses `{}` around blocks of code and we _choose_ if we indent code. Python uses `:` and indentation is required.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +* In JavaScript we choose to name variables in `camelCase`, whereas in Python we choose to name variables in `snake_case` (but in both langues we _could_ do either).
```suggestion
* In JavaScript we choose to name variables in `camelCase`, whereas in Python we choose to name variables in `snake_case` . In both langues we _could_ do either; this is called a "convention". 
```

I would tooltip on convention because you're going to talk a bunch about convention.

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +Let's take our "count containing words" JavaScript code from last week, and think about what it would look like in Python.
```suggestion
Recall our "count containing words" JavaScript code. Now think about what it would look like in Python.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +Let's think about what we're doing in this code. We're:
```suggestion
Think about what we're doing in this code.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +* Parsing command line flags - writing down what flags we expect to be passed, and reading values for them based on the actual command line.
Make this an activity and put the answer in a tab. Get them to write it out first themselves

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +These are the meaningful things we needed to do. If we wanted to solve the same problem with Python, we'd need to do all of these things.
```suggestion
These are the meaningful things we needed to do. To solve the same problem with Python, we'd still do all of these things.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +There are also some other things we did in our code, which were important, but not the point of the code. An example is, we imported some modules. We may need to import modules to write this code in
```suggestion
We did some other things in our code to make it work. For example, we imported some modules. To write this code in Python, we might need modules or we might not. Importing modules isn't one of our _goals_, it was just something we needed to do to help us.
```

Suggest moving out of code here to call on a concrete analogy. For example:

If I want to post a parcel, I go to my post office on the 85 bus. But my goal isn't to catch the bus; it's to post the parcel. I could go on my bike or take a taxi instead. I could even arrange for the postman to collect my parcel from my house. All these things are methods to reach my goal.

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/comparing-javascript-and-python/index.md
> +Whether we write the JavaScript `someArray.length` or the Python `len(some_array)` isn't a big difference - both do the same thing, they just look a little a little different.
```suggestion
Whether we write the JavaScript `someArray.length` or the Python `len(some_array)` isn't a big difference. Both lines do the same thing, they just express it differently. 
```

You could also explicitly tie this to human languages here as they almost all speak at least two.

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/converted-program/index.md
> +Finally, instead of calling `console.log`, in Python we call `print`.
```suggestion
Instead of calling `console.log`, in Python we call `print`.
```

Never start a text with finally - top tip. 😉

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/converted-program/index.md
> +This looks pretty similar to the JavaScript version. The essential shape is the same. But every line is a least a little bit different.
```suggestion
This looks similar to the JavaScript version. The shape is the same, but every line is a little bit different.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/converted-program/index.md
> +Some programming languages are a lot more different. But JavaScript and Python are, essentially, quite similar.
```suggestion
Some programming languages are very different, as different as Mandarin and English. But JavaScript and Python are, essentially, quite similar, like Spanish and Portugese.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/converting-javascript-to-python/index.md
> +In JavaScript, we wrote this code (note: there was some other code in between some of these lines):
```suggestion
In JavaScript, we wrote this code:
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/converting-javascript-to-python/index.md
> +The _essential_ goals here are to:
Again, make this an activity -- get them to identify the essential goals. 

Sorting and categorising activities are a key way humans build up their mental model, so let them get some foundations laid here. You could provide this in a few ways here

1  - give them all the goals and have them sort them into essential and accidental
2- have them identify the goals themselves and provide a key

Or another option I haven't considered...

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/counting-words/index.md
> +The list comprehension version of this works. The `filter` version gives an error. We can try to understand and fix the error, or just use the list comprehension version.
What do you want them to do here? Be clearer about what you want, don't hint.

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +Below we have a small NodeJS program. It is a bit like `wc`. It counts words in a file. Specifically, it counts words which contain a hyphen (`-`) character.
```suggestion
Below we have a small NodeJS program. It is a bit like `wc`. It counts words which contain a hyphen (`-`) character. Our program is called hyphenWC.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +It accepts one command line argument - the path of the file to read and count.
```suggestion
hyphenWC accepts one command line argument - the path of the file to read and count.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +Its output to stdout is just the number of words which contain a hyphen.
```suggestion
hyphenWC's output to stdout is the number of words which contain a hyphen.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +It uses the same language (JavaScript) as we've written before, but uses some different APIs.
```suggestion
hyphenWC uses the same language (JavaScript) we've written before, but uses some different APIs.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +This is loading some code from somewhere that isn't this file.
```suggestion
This `import` is loading some code from somewhere that isn't this file.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +The `process` module is built into NodeJS for managing our process. It can be used to do things like find out what arguments were passed to the process when it started, find out what user ran the pro
```suggestion
The `process` module is built into NodeJS for managing our process. We can use it to find out what arguments were passed to the process when it started, find out what user ran the process, exit the process, and more.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +This time, we're not importing the whole module. We are destructuring. The `node:fs` module exposes an object, and we are saying "import the `promises` property from the `fs` module, and bind it to t
```suggestion
This time, we're not importing the whole module. We are destructuring. The `node:fs` module exposes an object, and we are saying "import the `promises` property from the `fs` module, and bind it to the name `fs`".
```

tooltip on destructuring

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +It's the equivalent to us writing `import { promises } from "node:fs"; const fs = promises;`.
```suggestion
It is like writing `import { promises } from "node:fs"; const fs = promises;`.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +We are doing this because many of the things in the `fs` module don't support `async`/`await`, but `fs` has a sub-module called `promises` where everything supports `async`/`await`. Because we want t
Even though I know what this means, I don't feel I quite know what this means. Shall we go round on it again?

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +`process.exit` is a function which, when called, will stop our program running. Passing a non-zero number to it indicates that our program did not succeed.
Bit worried we are reproducing the docs here. How can we prompt them to look up what this simple function does first?

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +Reading the file at the path passed as an argument. We're using the `fs` module here from `node`, but everything else is just JavaScript - declaring a variable, using `await` because `fs.promises.rea
Maybe we hide some of these and have them do the play computer and then read yours? Not all, but one or two?

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/installing-npm-dependencies/index.md
> +The `package.json` contains a JSON object with information about your project. For now, we're just telling `npm` that our project is a module - this means we are allowed to use `import` in our progra
They have already used npm - call back to that and have them make a bridge to prior learning here.

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/reading-a-file/index.md
> +Comparing these shows some interesting differences, particularly around scope.
tooltip on scope

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/single-use-data-analysis/index.md
> +When we want to answer some question, sometimes it's useful to write a program that we may only use one time. Or we may re-use in the future.
```suggestion
When we want to answer some question, sometimes it's useful to write a program we may only use once. (Or we may re-use in the future.)
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/single-use-data-analysis/index.md
> +It's not always obvious whether it's easier to try to use tools that already exist, or to write our own.
Crying out for a concrete analogy here. Can you find an example in ordinary life like this? Sometimes it's easier to just make ourselves a sandwich than to go to a supermarket in a foreign country. Or something.

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/single-use-data-analysis/index.md
> +We can probably answer all of these questions with `jq`. We can also definitely write a program to answer all of these questions for us.
I really like this exercse.

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/using-python-dependencies/index.md
> +We're going to use the `cowsay` library to make a program which outputs a picture of a cow saying something.
❤️

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/using-python-dependencies/index.md
> +Now if we run `python3 cow.py` we don't get an error - we installed `cowsay` into our active virtual environment.
```suggestion
Run `python3 cow.py`. We don't get an error because we installed `cowsay` into our active virtual environment.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/using-python-dependencies/index.md
> +If we open a new terminal and run `python3 cow.py` we'll get an error again. Because we haven't activated a virtual environment.
```suggestion
Open a new terminal and run `python3 cow.py`. You will get an error again! This is because we haven't activated a virtual environment.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/using-python-dependencies/index.md
> +If we run `. .venv/bin/activate` and then `python3 cow.py` it will start working again.
```suggestion
Run `. .venv/bin/activate` and then `python3 cow.py`. It will start working again.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/using-python-dependencies/index.md
> +If we open a new terminal and run `python3 cow.py` we'll get an error again. Because we haven't activated a virtual environment.
```suggestion
Open a new terminal and run `python3 cow.py`. An error will occur because we haven't activated a virtual environment.
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/using-python-dependencies/index.md
> +If we try to run `python3 cow.py`, we'll get an error:
```suggestion
Run `python3 cow.py` and trigger this error:
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/virtual-environments/index.md
> +We often need to use libraries in Python.
```suggestion
We often use libraries in Python. 
```

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/virtual-environments/index.md
> +To install the dependencies, we need to make something called a virtual environment, where they will get installed to.
Define virtual environment. Use a simple concrete analogy and pop it in a blockquote.

2025-01-22 13:52 UTC, SallyMcGrath commented on common-content/en/module/tools/virtual-environments/index.md
> +First we need to _create_ the virtual environment. We do this by running `python3 -m venv .venv`. This will create a virtual environment in a directory named `.venv`. We could actually create it anyw
Identify this as a convention.

2025-01-24 14:08 UTC, illicitonion commented on common-content/en/module/tools/converting-javascript-to-python/index.md
> +If we want to work out how to do this in Python, we should focus on the essential goals. We may want to search for things like "Parse command line flags Python" and "Default argument values Python" b
I'm a bit torn on this.

Currently what I'm doing is giving them all of the building blocks (introducing `with`, introducing list comprehensions), and then having them apply them themselves in the backlog item to implement `cat`, `ls`, and `wc` in Python.

I do think it's a little unfriendly to not introduce things like `with` blocks and list comprehensions - this feels like useful reference material.

Maybe the middle-ground is to ask them to implement the whole thing at the bottom of this block, but then keep the following blocks which show them how to?

2025-01-26 14:17 UTC, 40thieves reviewed
Only got through Sprint 3 so far, but it's looking good.

2025-01-26 14:17 UTC, 40thieves commented on common-content/en/module/tools/installing-npm-dependencies/index.md
> +We told `commander` information about our program. We gave it a name, a description, and told it that it should allow a user to pass a flag name `-c` (or equivalently `--char`), and use a default val
I wonder if using hyphens is the best choice for this toy application - simply because here it could be confusing that we're using a hyphen as a value, whereas other places a hyphen is syntax.

Would switching to some other special character (`!` maybe?) be worth it?

2025-01-26 14:17 UTC, 40thieves commented on common-content/en/module/tools/first-nodejs-program/index.md
> +const wordsContainingHyphens = content.split(" ").filter((word) => word.indexOf("-") > -1).length;
```suggestion
const wordsContainingHyphens = content.split(" ").filter((word) => word.includes("-")).length;
```

2025-01-26 14:17 UTC, 40thieves commented on common-content/en/module/tools/first-nodejs-program/index.md
> +const wordsContainingHyphens = content.split(" ").filter((word) => word.indexOf("-") > -1).length;
Really nitpicky, but `wordsContaininingHyphens` implies that it's the actual list of words, but this is actually the count of words.

2025-01-26 14:17 UTC, 40thieves commented on common-content/en/module/tools/installing-npm-dependencies/index.md
> +We could have written all of this code ourselves. But using a library meant we could focus on what's unique about our problem, rather than spending time implementing flag parsing.
Don't 100% love this wording, but I think it is worth calling this out?

```suggestion
We could have written all of this code ourselves. But using a library meant we could focus on what's unique about our problem, rather than spending time implementing flag parsing.

This is a very common task in software development in the real world, joining together libraries (written by other people) to create some new unique solution.
```

2025-01-26 14:17 UTC, 40thieves commented on common-content/en/module/tools/read-about-operating-systems/index.md
> +You can do this on any Unix OS - you do not need a Raspberry Pi.
Do trainees know what this is? Worth tooltipping to explain that Linux and macOS are both flavours of Unix?

2025-01-27 15:55 UTC, illicitonion commented on common-content/en/module/tools/single-use-data-analysis/index.md
> +It's not always obvious whether it's easier to try to use tools that already exist, or to write our own.
I tried, with funnels...!

2025-01-27 15:57 UTC, illicitonion commented on common-content/en/module/tools/first-nodejs-program/index.md
> +Below we have a small NodeJS program. It is a bit like `wc`. It counts words in a file. Specifically, it counts words which contain a hyphen (`-`) character.
Rephrased to instead have a bunch of "Our program"s rather than "It"s or naming the program artificially.

2025-01-27 15:59 UTC, illicitonion commented on common-content/en/module/tools/first-nodejs-program/index.md
> +`process.exit` is a function which, when called, will stop our program running. Passing a non-zero number to it indicates that our program did not succeed.
I think this is their first introduction to the concept of an exit code (maybe it shouldn't be!), so I'm quite eager for it to be a clear simplification introducing this concept... I've added a "You can read more" reference.

2025-01-27 16:16 UTC, illicitonion commented on common-content/en/module/tools/first-nodejs-program/index.md
> +The `process` module is built into NodeJS for managing our process. We can use it to find out what arguments were passed to the process when it started, find out what user ran the process, exit the p
I think yes, but I'm struggling to come up with a useful wording for that tooltip... Got any suggestions?

2025-01-27 16:22 UTC, illicitonion commented on common-content/en/module/tools/using-npm-dependencies/index.md
> +So let's use a {{<tooltip title="library">}}A library is a collection of code that we can use, but which isn't part of our project.{{</tooltip>}} for this. We will use a library called `commander`.
Added a little note at the end of the next block, where we're already talking about "we could have written this ourselves", as another alternative.

2025-01-27 16:36 UTC, illicitonion commented on common-content/en/module/tools/first-nodejs-program/index.md
> +const wordsContainingHyphens = content.split(" ").filter((word) => word.indexOf("-") > -1).length;
Updated to default to counting words containing "e"s :) And renamed the var slightly clumsily

2025-01-30 11:38 UTC, illicitonion commented on common-content/en/module/tools/first-nodejs-program/index.md
> +Reading the file at the path passed as an argument. We're using the `fs` module here from `node`, but everything else is just JavaScript - declaring a variable, using `await` because `fs.promises.rea
Added a link :)

2025-01-30 11:49 UTC, illicitonion commented on common-content/en/module/tools/virtual-environments/index.md
> +To install the dependencies, we need to make something called a virtual environment, where they will get installed to.
Rather than an analogy, I did a comparison with `node_modules`, which even let me discuss configuration vs convention :)

2025-01-30 12:05 UTC, illicitonion commented on common-content/en/module/tools/counting-words/index.md
> +Using filter (`lambda` is a keyword for making an anonymous function in Python):
Converted this to a "Write a small standalone program to explore these approaches" exercise.

2025-02-02 20:56 UTC, SallyMcGrath commented on common-content/en/module/tools/first-nodejs-program/index.md
> +The `process` module is built into NodeJS for managing our process. We can use it to find out what arguments were passed to the process when it started, find out what user ran the process, exit the p
Process:

The running instance of your program: the code, state, memory, and system resources.

2025-02-02 20:56 UTC, SallyMcGrath approved these changes

2025-02-03 11:03 UTC, merged