1113 Register must include location and made available to local leaders
CodeYourFuture/curriculum pull request #1279
Opened 2024-12-30 21:09 UTC by SallyMcGrath

## What does this change?

pulls location data from course data files stored in org-cyf-theme
removes family name because it's too many fields

### Common Content?

- [ ] Block/s

### Common Theme?

- [ ] Yes

Issue number: #issue-number

### Org Content?

Module | Sprint | Page Type | Block Type

## Checklist

- [ ] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [ ] I have run my code to check it works
- [ ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Who needs to know about this?

2024-12-31 10:55 UTC, illicitonion requested changes
You'll also need to update `org-cyf-itp/tooling/netlify/functions/submission-created.js` to get the new field (and stop getting the removed field), and insert it into the row

2024-12-31 13:23 UTC, kfklein15 approved these changes
Looks good to me. 
Will this automatically update on the spreadsheet you created?
And will this spreadsheet also then include all other courses (ITD, Piscine, etc)?

2025-01-03 10:18 UTC, SallyMcGrath commented
> Looks good to me. Will this automatically update on the spreadsheet you created? And will this spreadsheet also then include all other courses (ITD, Piscine, etc)?

It can do. It doesn't yet because that wasn't in scope. 

But we can do that.

2025-01-03 10:53 UTC, kfklein15 commented
I can create a new ticket to update the spreadsheet. This way we can deliver this ticket. Thank you. Happy for it to be merged.

2025-01-27 15:04 UTC, illicitonion approved these changes
I made the changes - approving because I'm happy with them, but will let @SallyMcGrath merge

2025-01-27 21:30 UTC, SallyMcGrath reviewed
I'm merging but maybe we come back and tag this for a refactor. I don't think all this logic makes sense in this view

2025-01-27 21:30 UTC, merged

2025-01-28 11:59 UTC, illicitonion commented on common-theme/layouts/_default/day-plan.html
> +          {{ $parentsToTraverseToModule := $moduleSection.Params.parentsToTraverseToModule }}
We cannot. Because Go is Go. So obviously `0` is the same as absent, so `0 | default 1` evaluates to `1`. And being able to explicitly set this to `0` in a `Params` is the reason I added it in the first place.

I spent a while being sad about this before writing this code.

2025-01-28 12:00 UTC, illicitonion commented on common-theme/layouts/_default/day-plan.html
> +          {{ $moduleSection := $.Page.CurrentSection }}
I have no strong views on this, happy to go either way.