update time and blockData args passed to time partial
CodeYourFuture/curriculum pull request #221
Opened 2023-08-03 17:36 UTC by Dedekind561

## What does this change?

Module:
Week(s):

## Checklist

- [ ] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [ ] I have run my code to check it works
- [ ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

## Who needs to know about this?

## Rendered Pages

2023-08-04 10:53 UTC, SallyMcGrath requested changes
I think that instead of making this change here, the change should be in the time partial, which is currently accessing a .time argument but should access blockData.time from /block/data.html

2023-08-04 14:50 UTC, Dedekind561 commented
Cool, I've updated the time partial to read `time` property off the map that's passed to the time partial. I also merge the blockData and time attributes into a single map and then pass that to the partials in the block components.

2023-08-13 15:17 UTC, SallyMcGrath commented
I will move my revision to a new PR and stop blocking this on

2023-08-13 15:18 UTC, SallyMcGrath approved these changes
approved with the caveats documented - this is actually broken on live tho so this will do for now!!

2023-08-13 15:18 UTC, merged