Update index JS3 S4 Day PD.md
CodeYourFuture/curriculum pull request #226
Opened 2023-08-04 07:59 UTC by kfklein15

## What does this change?

Module: JS3
Week(s): 4

## Checklist

- [ ] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [ ] I have run my code to check it works
- [ ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

update PD content

## Who needs to know about this?

## Rendered Pages

2023-08-11 06:31 UTC, SallyMcGrath requested changes
More grammar issues. Spellcheck please!

Also, the study group task - that's a final project briefing because it's an interesting algorithm puzzle.  https://docs.google.com/document/d/1JzcbKOkOdFuZ6it6xX2dVyQ8fTmnfbkaL91YLT6w8mc/edit

2023-08-11 10:09 UTC, kfklein15 commented
Thanks, @SallyMcGrath 

I didn't understand what you meant by the FP briefing. Should we amend it?

2023-08-11 10:32 UTC, kfklein15 commented
Reviewed with grammarly on Docs.

2023-08-27 04:43 UTC, SallyMcGrath approved these changes

2023-08-27 04:43 UTC, merged