first rough draft of week 1
CodeYourFuture/curriculum pull request #351
Opened 2023-10-31 12:51 UTC by Dedekind561

## What does this change?

Module: JS3 
Week(s): 1

## Checklist

- [ ] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [ ] I have run my code to check it works
- [ ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

## Who needs to know about this?

## Rendered Pages

2023-10-31 12:53 UTC, Dedekind561 commented
I'm going to continue crafting this prep section over the next few days.

2023-10-31 15:52 UTC, SallyMcGrath requested changes
Mini copy edit -- I'm just here to get the details for the workshop (components-2)

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/call-stack/index.md
> +When playing computer, we can see that when we call `map` then the function `double` is also invoked too. So whilst one function is called we make a call to another function and then \*_return_ back
```suggestion
When playing computer, we can see that when we call `map` then the function `double` is also invoked. While one function is called, we make a call to another function and then _return_ to the previous frame. In other words, we need to keep track of which function is currently executing.
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/components/index.md
> +Our sub-goal is to be able to render _any_ show object in the DOM. To do this, we can wrap up create a show card component using a function.
```suggestion
Our sub-goal is to be able to render _any_ "show" object in the DOM. To do this, we can create a card component using a function.
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/components/index.md
> +function createShowCard() {
```suggestion
function createShowCard() {
```
```suggestion
function createCard(show) {
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/components/index.md
> +document.append(createShowCard(show1), createShowCard(show2)); // append the show cards to the DOM
```suggestion
document.append(createCard(show1), createCard(show2)); // append the cards to the DOM
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/components/index.md
> +Let's consider our code thus far:
```suggestion
Look at our code so far:
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/components/index.md
> +To build user interfaces, we break down the interface into smaller **components**. Functions are reusable blocks of code that we can use to do the same thing again and again. In a similar way, we bui
```suggestion
We already know that to build user interfaces, we break down the interface into smaller **components**. 

Functions are reusable blocks of code that we can use to do the same thing again and again. In a similar way, we build a complex user interface from **components**. Components are reusable blocks of the user interface. As functions allow us to reuse code again and again, we can implement components using functions.
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/components/index.md
> +Our sub-goal is to be able to render _any_ show object in the DOM. To do this, we can wrap up create a show card component using a function.
I just find the show card a bit hard to read as I keep reading it as showing the card, so I've made it card and passed show in.

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/data-ui/index.md
> +When we're building user interfaces we're often taking data and {{<tooltip title="rendering">}}**rendering** is the process of building a visual representation or interface from some code{{</tooltip>
```suggestion
User interfaces render data. {{<tooltip title="rendering">}}**rendering** is the process of building a visual representation or interface from some code{{</tooltip>}} We're going to start with some data and explore how this data structure is rendered on the page.
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/data-ui/index.md
> +Let's consider the following problem:
```suggestion

```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/data-ui/index.md
> +A typical event can be modelled as a JavaScript object with the following properties:
```suggestion
A show can be modelled as a JavaScript object with the following properties:
```

An event can be mistaken for an event in a program.

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/data-ui/index.md
> +So our list of event data can be modelled as an array of objects, each with a similar shape:
```suggestion
So our list of show data can be modelled as an array of objects, each with a similar shape:
```

If we're saying show, let's always say it wrt the data.

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/data-ui/index.md
> +const events = [
```suggestion
const shows = [
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/multiple-data/index.md
> +We can take a single datum and render it in the UI. However, we will often have larger data structures that hold collections of data that we want to render in the user interface. Let's consider the f
```suggestion
A datum is a single piece of data. We can take a single datum and render it in the UI. More often we render collections of data in the user interface.
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/multiple-data/index.md
> +We want to map over this data and render it in the user interface.
```suggestion
We want to loop over this data and render it in the user interface.
```
You've said map but not used map yet. Do you want to loop here?

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/one-to-one/index.md
> +At the moment, we have a one to one mapping between the array of data and the UI elements. We can take a group of UI elements and
```suggestion
At the moment, we have a one to one mapping between the array of data and the UI elements. Each item in the array matches a node in the UI.
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/single-datum/index.md
> +To break down this problem, let's define a sub-goal:
```suggestion
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/single-datum/index.md
> +We'll consider how to render a single datum before doing this for the whole list. We will start with an object like the one below:
```suggestion
To break down this problem, we'll render a single datum, before doing this for the whole list. Here's one show:
```

2023-10-31 15:52 UTC, SallyMcGrath commented on content/js3/blocks/using-map/index.md
> +`map` is a {{<tooltip title="higher order function">}} A **higher order function** is a function that takes another function as an argument or returns a new function{{</tooltip>}}. In this case, it m
```suggestion
`map` is a {{<tooltip title="higher order function">}} A **higher order function** is a function that takes another function as an argument or returns a new function{{</tooltip>}}. In this case, it means we pass a function as an argument to `map`. Then `map` will use this function to create a new array. 

Consider a list of numbers and a function `Math.round` that returns the rounded number. Our goal is to create a new array of rounded numbers from the starting array of numbers:
```

2023-11-08 12:29 UTC, SallyMcGrath requested changes
minor revisions

2023-11-08 12:29 UTC, SallyMcGrath commented on content/js3/blocks/single-datum/index.md
> +    director: "Martin Scoresese"
```suggestion
    director: "Martin Scorsese"
```

2023-11-08 12:29 UTC, SallyMcGrath commented on content/js3/blocks/using-map/index.md
> +In this example, our goal is to create a new array of doubled numbers given this array and function. In other words, we want to create the array `[10, 40, 60]`. Firstly, we can observe a one-to-one m
```suggestion
Our goal is to create a new array of doubled numbers given this array and function. We want to create the array `[10, 40, 60]`.  Look, it's another "one to one mapping"
```

2023-11-08 12:29 UTC, SallyMcGrath commented on content/js3/blocks/using-map/index.md
> +    director: "Martin Scoresee"
```suggestion
    director: "Martin Scorsese"
```

2023-11-08 12:29 UTC, SallyMcGrath commented on content/js3/blocks/using-map/index.md
> +    directory: "Carol Morley"
```suggestion
    director: "Carol Morley"
```

2023-11-09 11:17 UTC, Dedekind561 commented on assets/styles/03-elements/images.scss
> +  margin: 0;
Thanks for catching this.

2023-11-09 11:51 UTC, merged