Feature stopwatch
CodeYourFuture/curriculum pull request #741
Opened 2024-06-06 08:12 UTC by metinbaris

## What does this change?

Adds stopwatch for the time element whenever users onClick to the minutes.

Effects common content as feature
Issue number: #642 

## Checklist

- [x ] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [ x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Who needs to know about this?
@SallyMcGrath

2024-06-06 10:48 UTC, SallyMcGrath requested changes
Thanks so much for this. It's super fun! 🎉 

I think I'd like it to make a noise when the timer runs out. Play a little tada or bring bring sound?

As it stands, this isn't accessible. Please make it keyboard focusable and assign it the role button. You will also need to communicate the beginning and end of the countdown to the announcer. This can't really work by just making it a live region, as we don't want it counting down the whole time, that would be really distracting.

Can you have a think? (And let me know if you don't know how to do these things and I would be glad to support)

2024-06-06 15:00 UTC, metinbaris commented on common-theme/layouts/partials/time.html
> +<time class="c-block__time" datetime="P{{ $time }}M">{{ $time }} minutes ⏱</time>
@SallyMcGrath, I've tried to update the code based on your feedback. 

Could you please take a look at it again when you have some free time and check if it aligns with what you had in mind? If not, please feel free to edit the code directly :)

2024-06-23 10:27 UTC, SallyMcGrath commented on common-theme/layouts/partials/time.html
> +<time class="c-block__time" datetime="P{{ $time }}M">{{ $time }} minutes ⏱</time>
Looking now! :)

2024-07-13 08:51 UTC, SallyMcGrath approved these changes

2024-07-13 09:44 UTC, merged