edit to ITP prep git
CodeYourFuture/curriculum pull request #808
Opened 2024-07-13 17:05 UTC by fcaroline2020

## What does this change?

adds that git will be covered more indepth later and includes installation instructions

### Common Content?

No

### Common Theme?

Issue number: #782 

### Org Content?

Sprint

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Who needs to know about this?

2024-07-13 18:39 UTC, moneyinthesky approved these changes

2024-07-14 15:40 UTC, SallyMcGrath requested changes
When changing times for a day plan, change them on the day plan, not the central block.

2024-07-14 15:40 UTC, SallyMcGrath commented on common-content/en/module/induction/check-git-installation/index.md
> +You will use Git continually as a developer. We will cover Git more in depth later in the course, right now, we will just check that you have it installed.
```suggestion
You will use Git continually as a developer. We will cover Git in more depth later in the course. Right now, we will just check that you have it installed.
```

2024-07-14 15:40 UTC, SallyMcGrath commented on common-content/en/module/induction/check-git-installation/index.md
> +You will use Git continually as a developer. We will cover Git more in depth later in the course, right now, we will just check that you have it installed.
Comma splice

2024-07-31 20:32 UTC, JayMayer commented
@fcaroline2020 With Sally's suggestions, looks good to me. Can they be accepted to get this one merged?

2024-08-07 08:35 UTC, SallyMcGrath approved these changes

2024-08-07 08:35 UTC, merged