Update index FUN 3 Prep.md
CodeYourFuture/curriculum pull request #94
Opened 2023-06-13 09:59 UTC by kfklein15

## What does this change?

Module: Fundamentals
Week(s): 3

## Checklist

- [ ] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [ ] I have run my code to check it works
- [ ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

 Adding the prep for the presentation during the class

## Who needs to know about this?

## Rendered Pages

2023-06-13 18:29 UTC, SallyMcGrath requested changes

2023-06-13 18:29 UTC, SallyMcGrath commented on content/fundamentals/sprints/3/prep/index.md
>  name="Prepare Your Blocky Presentation"
```suggestion
name="Prepare Your Blockly Presentation"
```

But also please address the questions.

2023-06-14 10:41 UTC, kfklein15 commented on content/fundamentals/sprints/3/prep/index.md
> +src="https://github.com/CodeYourFuture/CYF-PD/tree/main/content/blocks/prepare-your-blocky-presentation"
They should be presenting the Tech Ed work they've done during Fundamentals, so not sure which one I should refer to. Probably CYF Blocks? (Old Syllabus is saying Blockly - sorry about the spelling error.)

2023-06-15 12:32 UTC, kfklein15 commented on content/fundamentals/sprints/3/prep/index.md
> +src="https://github.com/CodeYourFuture/CYF-PD/tree/main/content/blocks/prepare-your-blocky-presentation"
Updated it to CYF Blocks. Will do the CMS this afternoon

2023-06-21 05:38 UTC, merged